# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'User blocklist'
description: 'Checks if the user triggering the action is inside your block list'
author: 'mathnogueira'

branding:
  # https://actions-cool.github.io/github-action-branding/
  icon: 'file'
  color: 'blue'

inputs:
  blocked_users:
    description: List of users that cannot do operation
    required: true

outputs:
 result:
   description: true if user can do operation, false otherwise

runs:
  using: 'node12'
  main: 'dist/index.js'
