# Send us messages on slack when users from the community either open new issues or PRs
on:
  issues:
    types:
      - opened

jobs:
  notify_slack:
    name: Notify team
    runs-on: ubuntu-latest
    steps:
      - name: Check if it's team member
        id: is_team_member
        if: github.event.action == 'opened'
        uses: mathnogueira/user-blocklist@0.1.1
        with:
          blocked_users: mathnogueira
      - name: result
        run: |
          echo $ACTOR
          echo $RESULT
        env:
          ACTOR: ${{ github.actor }}
          RESULT: ${{ steps.is_team_member.outputs.result }}
